In [85]:
# numpy is a library specifically for calculating numbers or anything to do with numbers
# when importing numpy this is the code to use
import numpy as np

## basic Numpy Arrays

In [44]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [45]:
A = np.array([1, 2, 3, 4, 5, 5])
B = np.array([1, 2, 3, 4, 4.5, 5])

In [46]:
A[2]


np.int64(3)

In [47]:
B[-1]

np.float64(5.0)

In [48]:
A.dtype

dtype('int64')

In [49]:
B.dtype

dtype('float64')

In [50]:
C = np.array(['a', 'b', 'c', 'd','e'])

In [51]:
C.dtype

dtype('<U1')

## Dimensions and Shapes

In [52]:
a = np.array([
    [1, 2, 3, 9],
    [4, 5, 6, 7]
])

In [53]:
a.shape # since variable a is a  dimension, we get 2rows and 4 columns

(2, 4)

In [54]:
a.ndim # this will print 2 because its two dimensions

2

In [55]:
a.size # will print 8 because of the 8 numbers 

8

In [56]:
b = np.array([
    [ 
        [1, 2, 3, 4, 5, 6],
        [7, 8, 9, 10, 11, 12]
    ],
    [
        [13, 14, 15, 16, 17, 18],
        [18, 19, 20, 21, 22, 23]

    ]

])

In [57]:
b.ndim # this will print 4 dimensions because of the sets of 2

3

In [58]:
b.shape # this will first print 2 because of 2 rows in the first 2 then another 2 in the second then
         # print 6 because of the 6rows both have

(2, 2, 6)

In [59]:
b.size # this will print 24 because of the total numbers in all 4 rows

24

In [60]:
c = np.array([
    [
        [
        [1, 2, 3, 4, 5],
        [6, 7, 8, 9, 10]
    
        ]
    ], 
    [
            [
            [1, 2, 3, 4, 5],
            [6, 7, 8, 9, 10]
        
            ]
    ],
    [
            [
            [1, 2, 3, 4, 5],
            [6, 7, 8, 9, 10]
        
            ]
    ],
    [
            [
            [1, 2, 3, 4, 5],
            [6, 7, 8, 9, 10]
        
            ]
    ]

])

In [61]:
c.ndim # at this point you get it because its a 4 dimensions

4

In [62]:
c.shape

(4, 1, 2, 5)

In [63]:
c.size

40

## Indexing and Slicing of Matrices

In [64]:
d = np.array([
    [1, 2, 3, 4], #index 0
    [5, 6, 7, 8], #index 1
    [9, 10, 11, 12] #index 2 or -1
])

In [65]:
d[-1] # this will print the last list [9, 10, 11, 12]

array([ 9, 10, 11, 12])

In [66]:
d[1, 0] # the 1 will print the second row and 0 is the first number in the second row which is 5

np.int64(5)

In [67]:
d[-1, 1]

np.int64(10)

In [68]:
d.ndim

2

In [69]:
d[1:3] # gets the second row up to but not including the 3rd row which we do not have
       # basically just like a for loop *up to but not including*

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [70]:
d[:,:1] # prints all rows but only prints 1 column in each row

array([[1],
       [5],
       [9]])

In [71]:
d[1:, :2] # prints from row 2 but only prints two columns

array([[ 5,  6],
       [ 9, 10]])

In [72]:
d[2] = np.array([13, 14, 15, 16]) # replaces last row with the new numbers

In [73]:
print(d) # so when we print d you will see the changes

[[ 1  2  3  4]
 [ 5  6  7  8]
 [13 14 15 16]]


## Summary Statistics

In [74]:
d.sum()

np.int64(94)

In [75]:
d.mean()

np.float64(7.833333333333333)

In [76]:
d.std()

np.float64(5.112620550059322)

## Broadcasting and Vectorized Operations

In [77]:
d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [13, 14, 15, 16]])

In [78]:
d + 10

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [23, 24, 25, 26]])

In [79]:
d * 10

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [130, 140, 150, 160]])

## Boolean Arrays

In [80]:
d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [13, 14, 15, 16]])

In [81]:
d >= 15

array([[False, False, False, False],
       [False, False, False, False],
       [False, False,  True,  True]])

In [82]:
d[d >= 15]

array([15, 16])

## Linear algebra

In [87]:
AA = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15]
])

In [88]:
AA.dot

<function ndarray.dot>

In [89]:
BB = np.array([
    [10, 20, 30, 40, 50],
    [60, 70, 80, 90, 100],
    [111, 122, 132, 143, 151]
])

In [91]:
AA * BB

array([[  10,   40,   90,  160,  250],
       [ 360,  490,  640,  810, 1000],
       [1221, 1464, 1716, 2002, 2265]])